name: Unit Tests
description: Run Node.js unit tests

runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash

    - run: npm run build
      shell: bash

    - run: npm run test:unit
      shell: bash