name: Documentation and NPM package

on:
  workflow_call:
    inputs:
      node_lts_maintenance_version:
        description: "Maintenance Node LTS Version"
        required: true
        default: "18"
        type: string

      node_lts_active_version:
        description: "Active Node LTS Version"
        required: true
        default: "20"
        type: string

      node_lts_current_version:
        description: "Current Node LTS Version"
        required: true
        default: "22"
        type: string

  workflow_dispatch:
    inputs:
      doc_deploy:
        description: "Deploy Documentation"
        required: true
        default: true
        type: boolean

      npm_deploy:
        description: "Deploy to NPM"
        required: true
        default: true
        type: boolean

      node_lts_maintenance_version:
        description: "Maintenance Node LTS Version"
        required: true
        default: "18"
        type: string

      node_lts_active_version:
        description: "Active Node LTS Version"
        required: true
        default: "20"
        type: string

      node_lts_current_version:
        description: "Current Node LTS Version"
        required: true
        default: "22"
        type: string

jobs:
  doc-deploy:
    name: Documentation - Deploy
    if: ${{ (github.event_name != 'workflow_dispatch' || inputs.doc_deploy) && (github.ref_name == 'master' || github.ref_name == 'beta') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install additional libraries
        uses: ./.github/actions/install-packages

      - name: Extract references from context
        shell: bash
        id: extract-refs
        run: |
          echo "major-version=$(jq -r .version package.json | cut -d. -f 1)" >> $GITHUB_OUTPUT
          echo "repo=$(echo $GITHUB_REPOSITORY | cut -d/ -f 2)" >> $GITHUB_OUTPUT

      - name: Trigger documentation workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: kuzzleio
          repo: documentation
          github_token: ${{ secrets.ACCESS_TOKEN_CI }}
          workflow_file_name: child_repo.workflow.yml
          ref: ${{ github.ref_name == 'master' && 'master' || 'develop' }}
          client_payload: '{"repo_name":"${{ steps.extract-refs.outputs.repo }}","branch":"${{ github.head_ref }}","version":"${{ steps.extract-refs.outputs.major-version }}"}'

  npm-deploy:
    name: Build and deploy release on NPM.js
    if: ${{ (github.event_name != 'workflow_dispatch' || inputs.npm_deploy) && (github.ref_name == 'master' || github.ref_name == 'beta') }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install additional libraries
        uses: ./.github/actions/install-packages

      - name: Node version ${{ inputs.node_lts_current_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_lts_current_version }}
          registry-url: "https://registry.npmjs.org"
          scope: "@kuzzleio"

      - name: Install depedencies
        run: npm ci

      - name: Build depedencies
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GHP }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SEMANTIC_RELEASE_NPM_PUBLISH: "true"
          SEMANTIC_RELEASE_SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
        run: npx semantic-release
